In [4]:
import numpy as np
from opermat import *

print "\nSistema de Ecuaciones:"
print "50 = 5X3 + 2X2"
print "10-X1 = X3"
print "3X2 + 8X1 = 20"

print "\na) Forma Matricial Coeficientes"
M = np.array([[0, 2, 5, 50], [-1, 0, -1, -10], [8, 0, 3, 20]])
print M

print "\nb) Transpuesta Matriz Coeficientes"
op = OperMat()
T = op.transpuesta(M)
print T


Sistema de Ecuaciones:
50 = 5X3 + 2X2
10-X1 = X3
3X2 + 8X1 = 20

a) Forma Matricial Coeficientes
[[  0   2   5  50]
 [ -1   0  -1 -10]
 [  8   0   3  20]]

b) Transpuesta Matriz Coeficientes
[[  0.  -1.   8.]
 [  2.   0.   0.]
 [  5.  -1.   3.]
 [ 50. -10.  20.]]
