In [1]:
import numpy as np
from opermat import *

def asteriscos():
        print "\n\n", "* " * 4

A = np.array([[1, 6], [3, 10], [7, 4]])
B = np.array([[1, 3], [0.5, 2]])
C = np.array([[2, -2], [-3, 1]])
op = OperMat()

print "\nSe Definen 3 Matrices con Dimensiones:"
print "[A]: ",A.shape[0], " x ", A.shape[1] 
print A
print "\n[B]: ", B.shape[0], " x ", B.shape[1]
print B
print "\n[C]: ", C.shape[0], " x ", C.shape[1]
print C
print "\n#", "-" * 92, "#\n"

print "Productos Posibles: AB / AC / BC / CB"
print "-Producto AB:"
print "[A]:"
print A
print "\n[B]:"
print B
print "\n[A] x [B]= "
print op.producto(A, B)

asteriscos()
print "-Producto AC:"
print "[A]:"
print A
print "\n[C]:"
print C
print "\n[A] x [C]= "
print op.producto(A, C)

asteriscos()
print "-Producto BC:"
print "[B]:"
print B
print "\n[C]:"
print C
print "\n[B] x [C]="
print op.producto(B, C)

asteriscos()
print "-Producto CB:"
print "[C]:"
print C
print "\n[B]:"
print B
print "\n[C] x [B]="
print op.producto(C, B)


Se Definen 3 Matrices con Dimensiones:
[A]:  3  x  2
[[ 1  6]
 [ 3 10]
 [ 7  4]]

[B]:  2  x  2
[[ 1.   3. ]
 [ 0.5  2. ]]

[C]:  2  x  2
[[ 2 -2]
 [-3  1]]

# -------------------------------------------------------------------------------------------- #

Productos Posibles: AB / AC / BC / CB
-Producto AB:
[A]:
[[ 1  6]
 [ 3 10]
 [ 7  4]]

[B]:
[[ 1.   3. ]
 [ 0.5  2. ]]

[A] x [B]= 
[[  4.  15.]
 [  8.  29.]
 [  9.  29.]]


* * * * 
-Producto AC:
[A]:
[[ 1  6]
 [ 3 10]
 [ 7  4]]

[C]:
[[ 2 -2]
 [-3  1]]

[A] x [C]= 
[[-16.   4.]
 [-24.   4.]
 [  2. -10.]]


* * * * 
-Producto BC:
[B]:
[[ 1.   3. ]
 [ 0.5  2. ]]

[C]:
[[ 2 -2]
 [-3  1]]

[B] x [C]=
[[-7.  1.]
 [-5.  1.]]


* * * * 
-Producto CB:
[C]:
[[ 2 -2]
 [-3  1]]

[B]:
[[ 1.   3. ]
 [ 0.5  2. ]]

[C] x [B]=
[[ 1.   2. ]
 [-2.5 -7. ]]
