In [1]:
import math
import numpy as np

sum=0
n = np.array([[5,2,0], [1,0,1], [0,3,8]])#matriz a

b = np.array([[50],[10],[20]]) #matriz b

#TRANSPUESTA 

n1 = np.array([[5,1,0], [2,0,3], [0,1,8]])#matriz a

b2 = np.array([[50,10,20]]) #matriz b

print n
print b
print n1
print b2
    

[[5 2 0]
 [1 0 1]
 [0 3 8]]
[[50]
 [10]
 [20]]
[[5 1 0]
 [2 0 3]
 [0 1 8]]
[[50 10 20]]
